
__author__ = 'generated by py-ui4win'
# coding=gbk
import string, os, time

from PyUI import *
from MsgBox import *
from PyFrameBase import *
import UICommon
from CommonUtil import CommonUtils

class test(PyFrameBase):
    def __init__(self):
        super(test, self).__init__()
        self.clsName = self.__class__.__name__
        self.skinFileName = self.__class__.__name__ + '.xml'

    def GetSkinFile(self):
        return self.skinFileName

    def GetWindowClassName(self):
        return self.clsName

    def OnPrepare(self, sendor, wParam, lParam):
        self.LblIcon = self.PyFindLabel("LblIcon")
        self.Label201 = self.PyFindLabel("Label201")
        self.LblPhoneName = self.PyFindLabel("LblPhoneName")
        self.LblAndroilVersion = self.PyFindLabel("LblAndroilVersion")
        self.LblWarn = self.PyFindLabel("LblWarn")
        self.Label501 = self.PyFindLabel("Label501")
        self.LblStatus = self.PyFindLabel("LblStatus")
        self.BtnClose = self.PyFindButton("BtnClose")
        self.btnStartAnimation = self.PyFindButton("btnStartAnimation")
        self.btnStopAnimation = self.PyFindButton("btnStopAnimation")
        self.btnChooseInf = self.PyFindButton("btnChooseInf")
        self.btnInstallDriver = self.PyFindButton("btnInstallDriver")
        self.btnOpenLog = self.PyFindButton("btnOpenLog")
        self.btnClearLog = self.PyFindButton("btnClearLog")
        self.btnExcuteCompile = self.PyFindButton("btnExcuteCompile")
        self.btnDecSolution = self.PyFindButton("btnDecSolution")
        self.btnStartAnimation2 = self.PyFindButton("btnStartAnimation2")
        self.btnStopAnimation2 = self.PyFindButton("btnStopAnimation2")
        self.btnDriverDiagnose = self.PyFindOption("btnDriverDiagnose")
        self.btnEncrypt = self.PyFindOption("btnEncrypt")
        self.btnDriverInstall = self.PyFindOption("btnDriverInstall")
        self.btnPyTest = self.PyFindOption("btnPyTest")
        self.btnPyDec = self.PyFindOption("btnPyDec")
        self.ChkRoot = self.PyFindCheckBox("ChkRoot")
        self.ChkUIDebug = self.PyFindCheckBox("ChkUIDebug")
        self.ChkUIRelease = self.PyFindCheckBox("ChkUIRelease")
        self.ChkZsDebug = self.PyFindCheckBox("ChkZsDebug")
        self.ChkZsRelease = self.PyFindCheckBox("ChkZsRelease")
        self.ChkZsSign = self.PyFindCheckBox("ChkZsSign")
        self.PrgSdcard = self.PyFindProgress("PrgSdcard")
        self.Juhua = self.PyFindAnimation("Juhua")
        self.Juhua1 = self.PyFindAnimation("Juhua1")
        self.FlushRomTab = self.PyFindVerticalLayout("FlushRomTab")
        self.DriverInstallTab = self.PyFindVerticalLayout("DriverInstallTab")
        self.BasicInfoTab = self.PyFindVerticalLayout("BasicInfoTab")
        self.DriverDiagnoseTab = self.PyFindVerticalLayout("DriverDiagnoseTab")
        self.DecTab = self.PyFindVerticalLayout("DecTab")
        self.ListTab = self.PyFindVerticalLayout("ListTab")
        self.FunctionTabs = self.PyFindTabLayout("FunctionTabs")

    def OnNotify(self, sendor, sType, wParam, lParam):
        if sType == DUI_MSGTYPE_CLICK:
            if sendor == "BtnClose":
                pass
            if sendor == "btnStartAnimation":
                pass
            if sendor == "btnStopAnimation":
                pass
            if sendor == "btnChooseInf":
                pass
            if sendor == "btnInstallDriver":
                pass
            if sendor == "btnOpenLog":
                pass
            if sendor == "btnClearLog":
                pass
            if sendor == "btnExcuteCompile":
                pass
            if sendor == "btnDecSolution":
                pass
            if sendor == "btnStartAnimation2":
                pass
            if sendor == "btnStopAnimation2":
                pass
            if sendor == "btnDriverDiagnose":
                pass
            if sendor == "btnEncrypt":
                pass
            if sendor == "btnDriverInstall":
                pass
            if sendor == "btnPyTest":
                pass
            if sendor == "btnPyDec":
                pass
            if sendor == "ChkRoot":
                pass
            if sendor == "ChkUIDebug":
                pass
            if sendor == "ChkUIRelease":
                pass
            if sendor == "ChkZsDebug":
                pass
            if sendor == "ChkZsRelease":
                pass
            if sendor == "ChkZsSign":
                pass

        if sType == DUI_MSGTYPE_ITEMSELECT:
            pass
